### ISSUE TITLE
Improving workflow matrix definition

### ISSUE THREAD

**Issue by fabiocaccamo** [jefftriplett/python-github-actions-matrix-demo#6]
@jefftriplett thanks for sharing this action, it is indeed very useful.

Before using GitHub actions I used to use `TravisCI` together with `tox`.
Now I completely switched to GitHub workflows and I love them, except for the matrix definition.

Consider the following matrix I have in a `.tox` file:
```ini
py27-{dj17,dj18,dj19,dj110,dj111}-{sqlite,postgres},
py36-{dj18,dj19,dj110,dj111,dj20,dj21,dj22,dj30,dj31,dj32}-{sqlite,postgres},
py37-{dj20,dj21,dj22,dj30,dj31,dj32}-{sqlite,postgres},
py38-{dj22,dj30,dj31,dj32}-{sqlite,postgres},
py39-{dj22,dj30,dj31,dj32}-{sqlite,postgres},
py310-{dj32,dj40}-{sqlite,postgres},
```
This is very readable and easy to change, even if it defines a complex matrix, but its implementation as workflow matrix becomes very long and hard to read/maintain.

I'm wondering if it is possible to push the python/django/database matrix one step ahead, maybe by reading it from the `.tox` file of by parsing an action variable.

What do you think about it?

**Comment by jefftriplett** [comment]
It's hard to beat Tox's conciseness. I eventually switched this from a more dynamic include but my exclude rules were quickly outnumbering my more verbose include rules. 

I have seen several people invoke tox with different python versions in parallel to speed stuff up. I'm not sure if you have seen https://github.com/ymyzk/tox-gh-actions#workflow-configuration but this might an option for you. 

I'll double-check the docs to see if I'm missing something, but I'm debating writing something with [cog](https://github.com/nedbat/cog) to write these files out.

**Comment by fabiocaccamo** [comment]
Actually I'm already using `tox-gh-actions`, but the matrix is not well integrated into the workflow, multiple django versions are grouped by python version, furthermore coverage/codecov integrated inside tox stopped working. 
Considering that now I'm using it only for the matrix, I would like to avoid to use it at all if possible.

The main idea is:

- Write the matrix using the same tox syntax in a workflow env var
- Run a python script which:

    - parse the matrix definition
    - generate the workflow matrix 
    - store the matrix as json file
    
- Read the matrix using the [fromJSON](https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson) function.

**Comment by fabiocaccamo** [comment]
@jefftriplett in the end I wrote this GitHub action: https://github.com/marketplace/actions/create-matrix-action

Hope also you will find it useful, any feedback/contribution is well appreciated.
